<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FileExtensionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $defaults = [
            'created_at' => $now,
            'updated_at' => $now,
        ];

        $apps = [
            [
                'file_extension_name' => 'AIF',
                'file_extension' => 'aif',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => 'CDA',
                'file_extension' => 'cda',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => 'MID',
                'file_extension' => 'mid',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => 'MIDI',
                'file_extension' => 'midi',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => 'MP3',
                'file_extension' => 'mp3',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => 'MPA',
                'file_extension' => 'mpa',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => 'OGG',
                'file_extension' => 'ogg',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => 'WAV',
                'file_extension' => 'wav',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => 'WMA',
                'file_extension' => 'wma',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => 'WPL',
                'file_extension' => 'wpl',
                'file_type_id' => 1,
                'file_type_name' => 'Audio',
            ],
            [
                'file_extension_name' => '7Z',
                'file_extension' => '7z',
                'file_type_id' => 2,
                'file_type_name' => 'Compressed',
            ],
            [
                'file_extension_name' => 'ARJ',
                'file_extension' => 'arj',
                'file_type_id' => 2,
                'file_type_name' => 'Compressed',
            ],
            [
                'file_extension_name' => 'DEB',
                'file_extension' => 'deb',
                'file_type_id' => 2,
                'file_type_name' => 'Compressed',
            ],
            [
                'file_extension_name' => 'PKG',
                'file_extension' => 'pkg',
                'file_type_id' => 2,
                'file_type_name' => 'Compressed',
            ],
            [
                'file_extension_name' => 'RAR',
                'file_extension' => 'rar',
                'file_type_id' => 2,
                'file_type_name' => 'Compressed',
            ],
            [
                'file_extension_name' => 'RPM',
                'file_extension' => 'rpm',
                'file_type_id' => 2,
                'file_type_name' => 'Compressed',
            ],
            [
                'file_extension_name' => 'TAR.GZ',
                'file_extension' => 'tar.gz',
                'file_type_id' => 2,
                'file_type_name' => 'Compressed',
            ],
            [
                'file_extension_name' => 'Z',
                'file_extension' => 'z',
                'file_type_id' => 2,
                'file_type_name' => 'Compressed',
            ],
            [
                'file_extension_name' => 'ZIP',
                'file_extension' => 'zip',
                'file_type_id' => 2,
                'file_type_name' => 'Compressed',
            ],
            [
                'file_extension_name' => 'BIN',
                'file_extension' => 'bin',
                'file_type_id' => 3,
                'file_type_name' => 'Disk and Media',
            ],
            [
                'file_extension_name' => 'DMG',
                'file_extension' => 'dmg',
                'file_type_id' => 3,
                'file_type_name' => 'Disk and Media',
            ],
            [
                'file_extension_name' => 'ISO',
                'file_extension' => 'iso',
                'file_type_id' => 3,
                'file_type_name' => 'Disk and Media',
            ],
            [
                'file_extension_name' => 'TOAST',
                'file_extension' => 'toast',
                'file_type_id' => 3,
                'file_type_name' => 'Disk and Media',
            ],
            [
                'file_extension_name' => 'VCD',
                'file_extension' => 'vcd',
                'file_type_id' => 3,
                'file_type_name' => 'Disk and Media',
            ],
            [
                'file_extension_name' => 'CSV',
                'file_extension' => 'csv',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'DAT',
                'file_extension' => 'dat',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'DB',
                'file_extension' => 'db',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'DBF',
                'file_extension' => 'dbf',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'LOG',
                'file_extension' => 'log',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'MDB',
                'file_extension' => 'mdb',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'SAV',
                'file_extension' => 'sav',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'SQL',
                'file_extension' => 'sql',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'TAR',
                'file_extension' => 'tar',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'XML',
                'file_extension' => 'xml',
                'file_type_id' => 4,
                'file_type_name' => 'Data and Database',
            ],
            [
                'file_extension_name' => 'EMAIL',
                'file_extension' => 'email',
                'file_type_id' => 5,
                'file_type_name' => 'Email',
            ],
            [
                'file_extension_name' => 'EML',
                'file_extension' => 'eml',
                'file_type_id' => 5,
                'file_type_name' => 'Email',
            ],
            [
                'file_extension_name' => 'EMLX',
                'file_extension' => 'emlx',
                'file_type_id' => 5,
                'file_type_name' => 'Email',
            ],
            [
                'file_extension_name' => 'MSG',
                'file_extension' => 'msg',
                'file_type_id' => 5,
                'file_type_name' => 'Email',
            ],
            [
                'file_extension_name' => 'OFT',
                'file_extension' => 'oft',
                'file_type_id' => 5,
                'file_type_name' => 'Email',
            ],
            [
                'file_extension_name' => 'OST',
                'file_extension' => 'ost',
                'file_type_id' => 5,
                'file_type_name' => 'Email',
            ],
            [
                'file_extension_name' => 'PST',
                'file_extension' => 'pst',
                'file_type_id' => 5,
                'file_type_name' => 'Email',
            ],
            [
                'file_extension_name' => 'VCF',
                'file_extension' => 'vcf',
                'file_type_id' => 5,
                'file_type_name' => 'Email',
            ],
            [
                'file_extension_name' => 'APK',
                'file_extension' => 'apk',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'BAT',
                'file_extension' => 'bat',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'BIN',
                'file_extension' => 'bin',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'CGI',
                'file_extension' => 'cgi',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'PL',
                'file_extension' => 'pl',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'COM',
                'file_extension' => 'com',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'EXE',
                'file_extension' => 'exe',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'GADGET',
                'file_extension' => 'gadget',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'JAR',
                'file_extension' => 'jar',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'WSF',
                'file_extension' => 'wsf',
                'file_type_id' => 6,
                'file_type_name' => 'Executable',
            ],
            [
                'file_extension_name' => 'FNT',
                'file_extension' => 'fnt',
                'file_type_id' => 7,
                'file_type_name' => 'Font',
            ],
            [
                'file_extension_name' => 'FON',
                'file_extension' => 'fon',
                'file_type_id' => 7,
                'file_type_name' => 'Font',
            ],
            [
                'file_extension_name' => 'OTF',
                'file_extension' => 'otf',
                'file_type_id' => 7,
                'file_type_name' => 'Font',
            ],
            [
                'file_extension_name' => 'TTF',
                'file_extension' => 'ttf',
                'file_type_id' => 7,
                'file_type_name' => 'Font',
            ],
            [
                'file_extension_name' => 'AI',
                'file_extension' => 'ai',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'BMP',
                'file_extension' => 'bmp',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'GIF',
                'file_extension' => 'gif',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'ICO',
                'file_extension' => 'ico',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'JPG',
                'file_extension' => 'jpg',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'JPEG',
                'file_extension' => 'jpeg',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'PNG',
                'file_extension' => 'png',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'PS',
                'file_extension' => 'ps',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'PSD',
                'file_extension' => 'psd',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'SVG',
                'file_extension' => 'svg',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'TIF',
                'file_extension' => 'tif',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'TIFF',
                'file_extension' => 'tiff',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'WEBP',
                'file_extension' => 'webp',
                'file_type_id' => 8,
                'file_type_name' => 'Image',
            ],
            [
                'file_extension_name' => 'ASP',
                'file_extension' => 'asp',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'ASPX',
                'file_extension' => 'aspx',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'CER',
                'file_extension' => 'cer',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'CFM',
                'file_extension' => 'cfm',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'CGI',
                'file_extension' => 'cgi',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'PL',
                'file_extension' => 'pl',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'CSS',
                'file_extension' => 'css',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'HTM',
                'file_extension' => 'htm',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'HTML',
                'file_extension' => 'html',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'JS',
                'file_extension' => 'js',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'JSP',
                'file_extension' => 'jsp',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'PART',
                'file_extension' => 'part',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'PHP',
                'file_extension' => 'php',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'PY',
                'file_extension' => 'py',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'RSS',
                'file_extension' => 'rss',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'XHTML',
                'file_extension' => 'xhtml',
                'file_type_id' => 9,
                'file_type_name' => 'Internet Related',
            ],
            [
                'file_extension_name' => 'KEY',
                'file_extension' => 'key',
                'file_type_id' => 10,
                'file_type_name' => 'Presentation',
            ],
            [
                'file_extension_name' => 'ODP',
                'file_extension' => 'odp',
                'file_type_id' => 10,
                'file_type_name' => 'Presentation',
            ],
            [
                'file_extension_name' => 'PPS',
                'file_extension' => 'pps',
                'file_type_id' => 10,
                'file_type_name' => 'Presentation',
            ],
            [
                'file_extension_name' => 'PPT',
                'file_extension' => 'ppt',
                'file_type_id' => 10,
                'file_type_name' => 'Presentation',
            ],
            [
                'file_extension_name' => 'PPTX',
                'file_extension' => 'pptx',
                'file_type_id' => 10,
                'file_type_name' => 'Presentation',
            ],
            [
                'file_extension_name' => 'ODS',
                'file_extension' => 'ods',
                'file_type_id' => 11,
                'file_type_name' => 'Spreadsheet',
            ],
            [
                'file_extension_name' => 'XLS',
                'file_extension' => 'xls',
                'file_type_id' => 11,
                'file_type_name' => 'Spreadsheet',
            ],
            [
                'file_extension_name' => 'XLSM',
                'file_extension' => 'xlsm',
                'file_type_id' => 11,
                'file_type_name' => 'Spreadsheet',
            ],
            [
                'file_extension_name' => 'XLSX',
                'file_extension' => 'xlsx',
                'file_type_id' => 11,
                'file_type_name' => 'Spreadsheet',
            ],
            [
                'file_extension_name' => 'BAK',
                'file_extension' => 'bak',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'CAB',
                'file_extension' => 'cab',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'CFG',
                'file_extension' => 'cfg',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'CPL',
                'file_extension' => 'cpl',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'CUR',
                'file_extension' => 'cur',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'DLL',
                'file_extension' => 'dll',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'DMP',
                'file_extension' => 'dmp',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'DRV',
                'file_extension' => 'drv',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'ICNS',
                'file_extension' => 'icns',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'INI',
                'file_extension' => 'ini',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'LNK',
                'file_extension' => 'lnk',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'MSI',
                'file_extension' => 'msi',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'SYS',
                'file_extension' => 'sys',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => 'TMP',
                'file_extension' => 'tmp',
                'file_type_id' => 12,
                'file_type_name' => 'System Related',
            ],
            [
                'file_extension_name' => '3G2',
                'file_extension' => '3g2',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => '3GP',
                'file_extension' => '3gp',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'AVI',
                'file_extension' => 'avi',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'FLV',
                'file_extension' => 'flv',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'H264',
                'file_extension' => 'h264',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'M4V',
                'file_extension' => 'm4v',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'MKV',
                'file_extension' => 'mkv',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'MOV',
                'file_extension' => 'mov',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'MP4',
                'file_extension' => 'mp4',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'MPG',
                'file_extension' => 'mpg',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'MPEG',
                'file_extension' => 'mpeg',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'RM',
                'file_extension' => 'rm',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'SWF',
                'file_extension' => 'swf',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'VOB',
                'file_extension' => 'vob',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'WEBM',
                'file_extension' => 'webm',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'WMV',
                'file_extension' => 'wmv',
                'file_type_id' => 13,
                'file_type_name' => 'Video',
            ],
            [
                'file_extension_name' => 'DOC',
                'file_extension' => 'doc',
                'file_type_id' => 14,
                'file_type_name' => 'Word Processor',
            ],
            [
                'file_extension_name' => 'DOCX',
                'file_extension' => 'docx',
                'file_type_id' => 14,
                'file_type_name' => 'Word Processor',
            ],
            [
                'file_extension_name' => 'PDF',
                'file_extension' => 'pdf',
                'file_type_id' => 14,
                'file_type_name' => 'Word Processor',
            ],
            [
                'file_extension_name' => 'RTF',
                'file_extension' => 'rtf',
                'file_type_id' => 14,
                'file_type_name' => 'Word Processor',
            ],
            [
                'file_extension_name' => 'TEX',
                'file_extension' => 'tex',
                'file_type_id' => 14,
                'file_type_name' => 'Word Processor',
            ],
            [
                'file_extension_name' => 'TXT',
                'file_extension' => 'txt',
                'file_type_id' => 14,
                'file_type_name' => 'Word Processor',
            ],
            [
                'file_extension_name' => 'WPD',
                'file_extension' => 'wpd',
                'file_type_id' => 14,
                'file_type_name' => 'Word Processor',
            ],
        ];

        DB::table('file_extension')->insert(
            array_map(fn ($row) => $row + $defaults, $apps)
        );
    }
}
